services:

  bank-authorisation-server:
    container_name: bank-keycloak
    image: quay.io/keycloak/keycloak:26.2.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    command:
      - start-dev
#      - --import-realm
    ports:
      - "8090:8080"
#    volumes:
#      - ./keycloak/config/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    restart: unless-stopped
#    healthcheck:
#      test:
#        [
#          "CMD-SHELL",
#          'exec 3<>/dev/tcp/localhost/8080; echo -e "GET /health/ready HTTP/1.1\nhost: localhost:8080\n" >&3; timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR'
#        ]
#      interval: 10s
#      timeout: 10s
#      retries: 3
    networks:
      - backend

networks:
  backend:
    driver: bridge