server.port: 8080

spring:
  application:
    name: bankFront
  security:
    oauth2:
        client:
          provider:
            keycloak:
              issuer-uri: http://localhost:8090/realms/bankapp
          registration:
            bank_front:
              provider: keycloak
              authorizationGrantType: client_credentials
              client-id: bank_front
              client-secret: wKWXOS1YJgNvFHt6jHL2mjgmHHvGu2r0
              clientAuthenticationMethod: client_secret_post
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        health-check-path: /actuator/health
        healthCheckInterval: 15s

management.endpoints.web.exposure.include: info, health,refresh

logging:
  pattern.file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: DEBUG
    org.zalando.logbook: DEBUG