server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankapp
    username: postgres
    password: Inushing1980
    driver: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:database/schema.sql
      data-locations: classpath:database/data.sql

logging:
  pattern.file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: DEBUG
    org.zalando.logbook: DEBUG