server.port: 8084

spring:
  application:
    name: bankCash
  datasource:
    url: jdbc:postgresql://localhost:5432/cashapp
    username: postgres
    password: Inushing1980
  sql.init:
    mode: always
    schema-locations: classpath:schema.sql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/bankapp
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/bankapp
        registration:
          bank_cash:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: bank_cash
            client-secret: h09XeFhfvzA4wB68DyIwFx7zKM27aGP7
            clientAuthenticationMethod: client_secret_post
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
#        health-check-url: http://host.docker.internal:${server.port}/actuator/health

management.endpoints.web.exposure.include: info, health,refresh

logging:
  pattern.file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: DEBUG
    org.zalando.logbook: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: TIME_BASED
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 100ms