server.port: 8081

spring:
  application:
    name: bankAccounts
  config:
    import: 'optional:consul:'
  datasource:
    url: jdbc:postgresql://localhost:5432/accountapp
    username: postgres
    password: Inushing1980
  sql.init:
    mode: ALWAYS
    schema-locations: classpath:database/schema.sql
    data-locations: classpath:database/data.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/bankapp
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/bankapp
        registration:
          bank_accounts:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: bank_accounts
            client-secret: EF3owQYOVaDIDnBr14jkSt3kuResW6x0
            clientAuthenticationMethod: client_secret_post
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      config:
        enabled: true
        prefixes:
          - config

management.endpoints.web.exposure.include: info, health,refresh

logging:
  pattern.file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: DEBUG
    org.zalando.logbook: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: TIME_BASED
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 100ms