DROP TABLE IF EXISTS transactions_log CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS currencies CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name VARCHAR(256) NOT NULL,
  birth_day DATE NOT NULL,
  email VARCHAR(256) NOT NULL,
  password VARCHAR(1000) NOT NULL,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS currencies (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  short_name VARCHAR(3) NOT NULL,
  full_name VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  number VARCHAR(256) NOT NULL,
  amount NUMERIC(14,2) NOT NULL,
  currency_id INT NOT NULL REFERENCES currencies(id),
  user_id UUID NOT NULL REFERENCES users(id),
  created_at timestamp NOT NULL,
  is_active boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions_log (
  id UUID PRIMARY KEY,
  created_at timestamp NOT NULL,
  transaction_type VARCHAR(10) NOT NULL,
  from_account UUID NOT NULL REFERENCES accounts(id),
  to_account UUID NOT NULL REFERENCES accounts(id),
  amount_from NUMERIC(14,2) NOT NULL,
  amount_to NUMERIC(14,2) NOT NULL,
  is_succeed boolean NOT NULL
);