server.port: 8087

application:

spring:
  application:
    name: bank_exchange-generator
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/bankapp
        registration:
          bank_exchange-generator:
            provider: keycloak
            authorizationGrantType: bank_exchange-generator
            client-id: bank_accounts
            client-secret: N1VSP9EH3qUeGa98gzE4qxnFsTg7Q8eO
            clientAuthenticationMethod: client_secret_post
  cloud:
    consul:
      discovery:
        hostname: localhost
        port: 8500
        prefer-ip-address: true
        health-check-url: http://host.docker.internal:${server.port}/actuator/health

management.endpoints.web.exposure.include: info, health,refresh

logging:
  pattern.file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: DEBUG
    org.zalando.logbook: DEBUG