server.port: 8089

spring:
  application:
    name: bankNotifications
  config:
    import: 'optional:consul:'
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: Inushing1980
  sql.init:
    mode: ALWAYS
    schema-locations: classpath:schema.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/bankapp
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      config:
        enabled: true
        prefixes:
          - config

management.endpoints.web.exposure.include: info, health,refresh

logging:
  pattern.file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: DEBUG
    org.zalando.logbook: DEBUG