DROP TABLE IF EXISTS exchange_rates;
DROP TYPE currency;

CREATE TYPE currency AS ENUM ('RUB','USD','CNY');

CREATE TABLE exchange_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base CURRENCY NOT NULL,
  exchange CURRENCY NOT NULL,
  rate NUMERIC(14,2) NOT NULL CHECK(rate>=0),
  time timestamp,
  created_at timestamp DEFAULT NOW()
)
